### ISSUE TITLE
DSS 2.1.0 - Run Issue

### ISSUE THREAD

**Issue by henrybelk** [GlobalCyberAlliance/DomainSecurityScanner#3]
Downloaded 2.1.0 and tried to run dss, but getting the below error when running a query. Happens in PowerShell & CMD with and without administrator. Able to run the previous version of DRS still and it works.

`<nil> FTL An unexpected error occurred. error="apply option: open /etc/resolv.conf: open /etc/resolv.conf: The system cannot find the path specified."`

**Comment by wolveix** [comment]
Hi! Thanks for using our project.

This bug was introduced in the 2.1.0 release due to how nameservers were now being passed to the internal DNS scanner. This issue has now been addressed, and appears to be resolved for me locally.

Please try using this again, and let me know if you continue to encounter the same problems.

**Comment by henrybelk** [comment]
2.1.1 resolved the issue. Thanks!

Took a bit to time out as I block external DNS servers other than my upstream. Once I saw that it couldn't reach 8.8.8.8, I was able to use -n to specify my internal DNS.
